import type { NextPage } from "next";
import Head from "next/head";
import ButtonLink from "../components/Button";
import NewsCard from "../components/Card";
import Footer from "../components/Footer";
import NextNode from "../components/NextNode";
import styles from "../styles/Home.module.css";


const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">CryptoNita</a>
        </h1>

        <div className={styles.grid}>
          <NextNode
            title={"Documentation"}
            text={"Hola buenas"}
            link={"https://"}
          ></NextNode>
          <NextNode
            title={"GitHub Backend"}
            text={"Repo for the CryptoNita backend."}
            link={"https://github.com/Luis4609/cryptonita-backend"}
          ></NextNode>
          <NextNode
            title={"Documentation"}
            text={"Hola buenas"}
            link={"https://"}
          ></NextNode>
          <NextNode
            title={"Cards MUI"}
            text={"Documentation for the Card component from MUI."}
            link={"https://mui.com/material-ui/react-card/#main-content"}
          ></NextNode>
        </div>
        <NewsCard
          title={"News"}
          description={"Nueva noticia sobre Bitcoin"}
          imageurl={"vespa.jpg"}
        ></NewsCard>
        <ButtonLink url="landingpage" text="Landing page"></ButtonLink>
      </main>
      <Footer></Footer>
    </div>
  );
};

export default Home;
